### ISSUE TITLE
We can find the file 

### ISSUE THREAD

**Issue by maximedotair** [kupietools/excel-liquidity-pool-simulator#3]
It's here : 

https://github.com/ApopheniaPays/excel-liquidity-pool-simulator/blob/81d39b7e9f9a1fe47b1f3666d361c4bd871ccfe7/Liquidity%20Pool%20simulator%20DEMO.rev%204.xlsx

**Comment by ApopheniaPays-psnl** [comment]
LOL, sorry for the late reply. Thanks for pointing this out... I'm not very experienced with Github, I don't really know the ins and outs. I had actually decided a while back that I was over my grudge (although user @beechfuzz remains and always will be on my shitlist just for acting so childish towards me) and meant to repost the file publicly, although I hadn't gotten around to it yet. Thanks for the pointing this out, anyway!
